name: Resume Review
description: Please review my resume on a live stream
title: "[REVIEW]"
labels: [resume review, livestream]
body:
  - type: markdown
    attributes:
      value: "**Remove all personal data, otherwise, the resume will be deleted**"
  - type: input
    id: link
    attributes:
      label: Resume link
      placeholder: "e.g.: https://drive.google.com/file/d/<file-id>/view"
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
       You can also join our Discord community [here](https://discord.gg/RXhJ2Rnbxm)
        Feel free to check out other cool repositories of the Codame IT Solutions [here](https://github.com/codameio)
